config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      post "new_comment", to: "comments#create", on: :member
      post "like_post", to: "likes#create", on: :member
      post "like_post", to: "likes#create", on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index], defaults: {format: :json} do
        resources :comments, only: [:index, :create]
      end
    end
  end

  resources :comments, only: [:destroy]
 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :jwt_authenticatable,
         :registerable,
         jwt_revocation_strategy: JwtDenylist

  has_many :posts
  has_many :likes
  has_many :comments

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def return_three_posts
    posts.order('created_at Desc').limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>users</h1>

<ul>

<% @users.each do |user| %>
  <li>
  <%= link_to  user_path(user.id) do %>

  <div class="card">
  <div>
  <%= image_tag ("#{user.photo}") %>
  </div>
  <h2>
  <%= user.name %>
  </h2>
  <p>Number of posts: <%= user.posts_counter %></p>
  </div>
  <% end %>

  </li>
<% end %>
 </ul>

app/views/users/show.html.erb
<div class="show-user">
  <h1>show user data</h1>
  <ul>
    <li>
      <div class="card">
        <div>
          <%= image_tag ("#{@user.photo}") %>
        </div>
        <h2>
          <%= @user.name %>
        </h2>
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
    </li>
  </ul>
  <div>
    <h3>Bio</h3>
    <p>
      <%= @user.bio %>
    </p>
  </div>
  <div>
    <h2>Posts:</h2>
    <ul>
      <% @user.return_three_posts.each do |post| %>
        <li>
        <% if can? :destroy, post %>
        <%= button_to 'Delete Post' , user_post_path(@user, post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
          <div class='post-card'>
            <div>
              <h3>
                <%= post.title %>
              </h3>
            </div>
            <p>
              <%= post.text %>
            </p>
            <div>
              <span>Comments:
                <%= post.comments_counter %>
              </span>
              <span> Likes:
                <%= post.likes_counter %>
              </span>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <%= link_to 'See all posts', user_posts_path(@user.id) , class:'btn'%>
</div>