config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      post "new_comment", to: "comments#create", on: :member
      post "like_post", to: "likes#create", on: :member
      post "like_post", to: "likes#create", on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index], defaults: {format: :json} do
        resources :comments, only: [:index, :create]
      end
    end
  end

  resources :comments, only: [:destroy]
 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments

  after_save :update_post_counter
  after_destroy :update_posts_counter_after_destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def return_five_comments
    comments.order('created_at Desc').limit(5)
  end

  private

  def update_post_counter
    user.increment!(:posts_counter)
  end

  def update_posts_counter_after_destroy
    user.decrement!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    # @post = User.find(params[:user_id]).posts.find(params[:id])
    @post = User.find(params[:user_id]).posts.includes(:comments).find(params[:id])
    authorize! :read, @post
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
    render :new, locals: { post: @post }
  end

  def create
    authorize! :create, @post
    @user = User.find(params[:user_id])
    add_post = @user.posts.new(post_params)
    add_post.comments_counter = 0
    add_post.likes_counter = 0
    respond_to do |format|
      format.html do
        if add_post.save
          flash[:success] = 'Post created successfully'
          redirect_to user_posts_url
        else
          flash.now[:error] = 'Error: Post could not be created'
          render :new, locals: { post: add_post }
        end
      end
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy
    authorize! :read, @post

    flash[:success] = 'Post deleted successfully'
    redirect_to root_url
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end
end

app/helpers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        @posts = Post.all.order('created_at DESC')
        render json: { success: true, data: { comments: @posts } }
      end

      def show
        @show_post = current_user.posts.includes(:comments)
        render json: { success: true, data: { comments: @show_post } }
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <li>
    <div class="card">
      <div>
        <%= image_tag ("#{@user.photo}") %>
      </div>
      <h2>
        <%= @user.name %>
      </h2>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </li>
</ul>

  <ul>
      <% @user.posts.each do |post| %>
      <%= link_to   user_post_path(@user.id, post.id) do %>
        <li>
          <div class='post-card'>
            <div>
              <h3>
                <%= post.title %>
              </h3>
            </div>
            <p>
              <%= post.text %>
            </p>
            <div>
              <span>Comments:
                <%= post.comments_counter %>
              </span>
              <span> Likes:
                <%= post.likes_counter %>
              </span>
            </div>
            <div class="comment">
            
            
            <% post.comments.each do |comment| %>
              <p>
            <%= comment.text %>
            </p>
            <% end %>
            
            </div>
          </div>
        </li>
        <% end %>
      <% end %>
    </ul>
<% if can? :destroy, Post %>

    <%= link_to 'Create-post', new_user_post_path, class:'btn' %>
<% end %>

app/views/posts/new.html.erb
<h1>Create new post</h1>
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post, class: "form" do |form| %>
  <div class="mb-3">
    <%= form.label :post_title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :your_post %>
    <%= form.text_area :text, class: "form-control text" %>
  </div>
  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1> posts show page</h1>

 <ul>
        <li>
          <div class='post-card'>
            <div>
              <h3 class='title'>
                <%= @post.title %>
              </h3>
            </div>
            <p class='comment'>
              <%= @post.text %>
            </p>
            <div>
              <span>Comments:
                <%= @post.comments_counter %>
              </span>
              <span> Likes:
                <%= @post.likes_counter %>
              </span>
            </div>
            <div class="comment">
            <%= button_to 'Add Like', like_post_user_post_url(@post), method: "put" ,class:'like-btn'%>
            
            <% @post.comments.each do |comment| %>
              <div class='comment'>
            comment: <%= comment.text %> by: 
            <%= comment.user.name %>
            </div>
            <% if can? :destroy, comment %>
           <span> <%=button_to 'Delete Comment' , comment, method: :delete, data: { confirm: 'Are you sure?' }%></span> 
            <% end %>
            <% end %>
            
            </div>
          </div>
        </li>      
    </ul>

     <h1>Leave your comment here...</h1>
  <%= form_with url: new_comment_user_post_path do |form| %>
    <div class="mb-3">
      <%= form.text_area :text, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>